#!/bin/sh
ssh ubuntu@13.124.150.125 <<EOF
    cd ~/jenkins-test
    git pull origin master
    # curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    # . ~/.nvm/nvm.sh
    # nvm install 14.17.6
    # npm install
    # npm install -g pm2
    pm2 startOrRestart ecosystem.config.js
EOF